### ISSUE TITLE
Create content area

### ISSUE THREAD

**Issue by kennho** [NUSComputingDev/acad.nuscomputing.com#3]
As stated in the title.
The content area is the part shown in the image below.
![acad_website_mockup_content](https://cloud.githubusercontent.com/assets/10682388/13710751/0309bda2-e7f6-11e5-9c52-415be632ff6e.png)

Below are the colors used:
![acad_website_mockup with legend](https://cloud.githubusercontent.com/assets/10682388/13710781/1ed1b27e-e7f6-11e5-88a3-063049956b6a.png)

The whole page should look like the image above without all the hex values and boxes.
These images are also available on the folder in google drive. Feel free to ask any questions.

**Comment by nhan-ng** [comment]
Please refer to pull request #8
